mybatis:
  mapper-locations: classpath*:mapper/*.xml
  config-location: classpath:SqlMapConfig.xml
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://47.101.140.115:3307/mall?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    minPoolSize: 2
    maxPoolSize: 10
    maxIdleTime: 1800000
    acquireIncrement: 3
    maxStatements: 1000
    initialPoolSize: 3
    idleConnectionTestPeriod: 30
    acquireRetryAttempts: 30
    acquireRetryDelay: 1000
    breakAfterAcquireFailure: false
    testConnectionOnCheckout: true
    testConnectionOnCheckin: true
  rabbitmq:
    host: 47.101.140.115
    username: admin
    password: admin
    port: 5672
    publisher-confirms: true
    virtual-host: /
  redis:
    port: 6379
    host: 192.168.25.193